name: mymeta
description: MyMeta - Professional media file metadata manager and renamer
publish_to: 'none'
version: 1.6.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  file_picker: ^8.0.0
  path: ^1.8.3
  desktop_drop: ^0.4.4
  sqflite_common_ffi: ^2.3.0
  sqlite3_flutter_libs: ^0.5.0
  provider: ^6.0.5
  window_manager: ^0.3.5
  shared_preferences: ^2.2.2
  url_launcher: ^6.2.1
  http: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
